name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: pr-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Next.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Type-check opcional (se ejecuta solo si existe tsconfig.json)
      - name: Type check (optional)
        if: hashFiles('tsconfig.json') != ''
        run: npx tsc --noEmit

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build
